# Generated by Django 3.1.2 on 2021-02-01 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('booking_date_time', models.DateTimeField(auto_now_add=True)),
                ('table_book_time', models.TimeField()),
                ('table_book_date', models.DateField()),
                ('num_of_person', models.IntegerField()),
                ('contact_num', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
