# Generated by Django 3.1.2 on 2021-02-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTH', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='contact_num',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='num_of_person',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='table_book_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booktable',
            name='table_book_time',
            field=models.TimeField(null=True),
        ),
    ]
