# Generated by Django 3.1.2 on 2021-02-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTH', '0003_auto_20210201_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booktable',
            name='table_book_date',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
