# Generated by Django 3.1.2 on 2021-02-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTH', '0004_auto_20210201_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='booktable',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
