# Generated by Django 3.1.2 on 2021-02-01 19:21

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('RTH', '0005_booktable_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('table_id', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('num_of_person', models.IntegerField()),
                ('booking_name', models.CharField(max_length=100)),
                ('total_amount', models.CharField(max_length=100)),
                ('list_of_people', django_mysql.models.ListCharField(models.CharField(max_length=10), max_length=66, size=6)),
            ],
        ),
    ]
