# Generated by Django 3.1.2 on 2021-02-01 19:42

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('RTH', '0006_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='list_of_people',
        ),
        migrations.AddField(
            model_name='order',
            name='each_contribution',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
