# Generated by Django 3.1.2 on 2021-02-02 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RTH', '0007_auto_20210202_0112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='num_of_person',
        ),
    ]
