# Generated by Django 3.1.2 on 2021-02-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RTH', '0008_remove_order_num_of_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rating', models.CharField(max_length=10)),
                ('address', models.TextField()),
            ],
        ),
    ]
